INSERT INTO USERS (ID, JOIN_DATE, NAME, PASSWORD, SSN)
VALUES (900, CURRENT_TIMESTAMP, 'jinsol1', '0000', '12313');
INSERT INTO USERS (ID, JOIN_DATE, NAME, PASSWORD, SSN)
VALUES (902, CURRENT_TIMESTAMP, 'jinsol2', '1111', '31231');

INSERT INTO USERS (ID, JOIN_DATE, NAME, PASSWORD, SSN)
VALUES (903, CURRENT_TIMESTAMP, 'jinsol3', '2412', '31232');


INSERT INTO post(DESCRIPTION, USER_ID) VALUES('My first post', 900);
INSERT INTO post(DESCRIPTION, USER_ID) VALUES('My second post', 900);


